//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetRolesPermiso
    {
        public string idNetRoles { get; set; }
        public short idPermiso { get; set; }
    
        public virtual Permiso Permiso { get; set; }
    }
}
