//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.ReqFuncional = new HashSet<ReqFuncional>();
            this.Usuario2 = new HashSet<Usuario>();
        }

        [Display(Name = "Nombre:")]
        public string nombre { get; set; }

        [Display(Name = "Descripción:")]
        public string descripcion { get; set; }

        [Display(Name = "Fecha de Inicio:")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> fechaInicio { get; set; }

        [Display(Name = "Fecha Final:")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> fechaFinal { get; set; }

        [Display(Name = "Líder:")]
        public string lider { get; set; }

        [Display(Name = "Estado:")]
        public string estado { get; set; }

        [Display(Name = "Cliente:")]
        public string Cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqFuncional> ReqFuncional { get; set; }
        public virtual Usuario Usuario { get; set; }
        [Display(Name = "Desarrolladores:")]
        public virtual Usuario Usuario1 { get; set; }
        [Display(Name = "Desarrolladores:")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario2 { get; set; }
    }
}
