//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Solicitud
    {
        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
        [Display(Name = "Estado")]
        [Required(ErrorMessage = "El estado es un campo requerido.")]
        public string estado { get; set; }
        [Display(Name = "Razon")]
        [Required(ErrorMessage = "Razon es un campo requerido.")]
        public string razon { get; set; }
        [Display(Name = "Realizado Por")]
        [Required(ErrorMessage = "Realizado por es un campo requerido.")]
        public string realizadoPor { get; set; }
        [Display(Name = "Aprobado Por")]
        public string aprobadoPor { get; set; }
        [Display(Name = "Versión")]
        public short versionRF { get; set; }
        [Display(Name = "ID Requerimiento")]
        public int idReqFunc { get; set; }
        [Display(Name = "Nombre Proyecto")]
        public string nomProyecto { get; set; }
        [Display(Name = "Nombre Requerimiento")]
        public string nombreRF { get; set; }
        [Display(Name = "Sprint")]
        public Nullable<byte> sprintRF { get; set; }
        [Display(Name = "Modulo")]
        public Nullable<byte> moduloRF { get; set; }
        [Display(Name = "Fecha Inicio")]
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaInicialRF { get; set; }
        [Display(Name = "Fecha Final")]
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaFinalRF { get; set; }
        [Display(Name = "Observaciones")]
        public string observacionesRF { get; set; }
        [Display(Name = "Descripción")]
        public string descripcionRF { get; set; }
        [Display(Name = "Esfuerzo")]
        public Nullable<short> esfuerzoRF { get; set; }
        [Display(Name = "Prioridad")]
        public Nullable<short> prioridadRF { get; set; }
        [Display(Name = "Imagen")]
        public byte[] imagenRF { get; set; }
        [Display(Name = "Responsable")]
        public string responsable1RF { get; set; }
        [Display(Name = "Responsable")]
        public string responsable2RF { get; set; }
    
        public virtual HistVersiones HistVersiones { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }

        public string razonPreview { get { return razon.Length > 10 ? razon.Substring(0, 10) + "..." : razon; } }
    }
}
