//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public string razon { get; set; }
        public string realizadoPor { get; set; }
        public string aprobadoPor { get; set; }
        public short versionRF { get; set; }
        public int idReqFunc { get; set; }
        public string nomProyecto { get; set; }
    
        public virtual HistVersiones HistVersiones { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
