//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Telefono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public string usuario { get; set; }
        [StringLength(8)]
        [RegularExpression(@"^[0-9]{8,8}$", ErrorMessage = "Longitud del teléfono debe ser de 8 dígitos")]
        public string numero { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
